baseURL = "https://tfq799qpbn-cmd.github.io/firstweb/"
languageCode = "zh-Hans"
theme = "moments"
themesDir = "themes"
paginate = 10
paginatePath = '.'

[params]
    title = "microcosm"
    signature = "为明天的太阳而活！"
    cover = "cover.jpg"

    name = "哈哈"
    avatar = "avatar.png"